In [13]:
import pickle

with open("../data/processed/ibkr_2022_2025.pkl", "rb") as f:
    ib = pickle.load(f)

df = ib["2022"]["Trades.Stocks"]

In [14]:
df

,Header,DataDiscriminator,Asset Category,Currency,Symbol,Date/Time,Quantity,T. Price,C. Price,Proceeds,Comm/Fee,Basis,Realized P/L,MTM P/L,Code
0,Data,Order,Stocks,EUR,3BUS,"2022-09-28, 04:46:51",30,62.96,60.6,-1888.8,-3,1891.8,0,-70.8,O
1,Data,Order,Stocks,EUR,3BUS,"2022-09-30, 09:46:08",-30,59,59.74,1770,-3,-1891.8,-124.8,-22.2,C
2,SubTotal,,Stocks,EUR,3BUS,,0,,,-118.8,-6,0,-124.8,-93,
3,Data,Order,Stocks,EUR,3DES,"2022-06-17, 10:37:23","2,000",1.425,1.4065,-2850,-3,2853,0,-37,O
4,Data,Order,Stocks,EUR,3DES,"2022-06-27, 04:22:05","-2,000",1.322,1.367,2644,-3,-2853,-212,-90,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,Data,Order,Stocks,USD,VRNS,"2022-02-03, 09:51:01",70,37.2,36.5,-2604,-1,2605,0,-49,O
182,Data,Order,Stocks,USD,VRNS,"2022-11-04, 09:59:07",-70,16.24,16.01,1136.8,-1.03513272,-2605,-1469.235133,16.1,C
183,SubTotal,,Stocks,USD,VRNS,,0,,,-1467.2,-2.03513272,0,-1469.235133,-32.9,
184,Total,,Stocks,USD,,,,,,28513.006,-45.642701913,-33860.619937,-5393.256638,324.646,
185,Total,,Stocks,EUR,,,,,,28088.25003352,-42.887317635,-33841.884325911,-5796.521609224,321.89781672,